create table if not exists telemetry_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  captured_at timestamptz not null,
  reactor_id text not null,
  reactor_name text not null,
  location text not null,
  status text not null,
  temperature double precision not null,
  ph double precision not null,
  pressure double precision not null,
  flow_rate double precision not null,
  enzyme_activity double precision not null,
  substrate_concentration double precision not null,
  product_yield double precision not null,
  dissolved_oxygen double precision not null,
  uptime_hours double precision not null default 0,
  unresolved_alerts integer not null default 0
);

create index if not exists telemetry_events_reactor_created_idx
on telemetry_events (reactor_id, created_at desc);

